name: themoviedb
description: baza рузоперевозок
publish_to: 'none' 
version: 1.0.20+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter     
  flutter_secure_storage: ^4.2.1
  dio: ^4.0.0
  json_annotation: ^4.0.0 #для автоматической генерации from/to json
  intl: ^0.17.0 #отвечает за парсинг дат
  cupertino_icons: ^1.0.2
  adaptive_action_sheet: ^2.0.0
  bs_flutter: any
  http: ^0.13.4
  rflutter_alert: ^2.0.4
  flutter_map:
  flutter_map_tappable_polyline: ^3.1.0
  latlong2: ^0.8.0
  image_picker: ^0.8.4+4
  photo_view: ^0.13.0
  syncfusion_flutter_charts: ^19.4.47
  google_maps_flutter_web: ^0.3.2
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.1
  geolocator: ^7.0.7
  permission_handler: ^8.3.0
  provider: ^5.0.0
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_api_headers: ^1.0.0
  tuple: ^2.0.0-nullsafety.0
  multiselect_formfield: ^0.1.6
  dropdown_search: ^0.6.3
  month_picker_dialog: ^0.4.0
  flutter_datetime_picker: ^1.5.1
  rating_dialog: ^2.0.3
  url_launcher: 
  list_tile_switch:    
  mask_text_input_formatter: ^2.1.0
  webview_flutter: ^3.0.4
  bubble_tab_indicator: ^0.1.4
  web_socket_channel: ^2.1.0
  flutter_local_notifications: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/AppIcon.png"
  build_runner: ^2.0.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - images/